// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJHMbOwyEgVRTPbVu4DnU4-ihrvzzihg',
    appId: '1:664746257926:web:a8fc3e18656c68759c5d87',
    messagingSenderId: '664746257926',
    projectId: 'example-33ebf',
    authDomain: 'example-33ebf.firebaseapp.com',
    storageBucket: 'example-33ebf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgY1oimqiu2o9EyM1NOSkdI-UJlMp2eI',
    appId: '1:664746257926:android:0130bf3ec7d4c81e9c5d87',
    messagingSenderId: '664746257926',
    projectId: 'example-33ebf',
    storageBucket: 'example-33ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV26biWjuQvjItVpBSjYHb8-1vB0VGaBA',
    appId: '1:664746257926:ios:ef02fc88542bc9e09c5d87',
    messagingSenderId: '664746257926',
    projectId: 'example-33ebf',
    storageBucket: 'example-33ebf.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV26biWjuQvjItVpBSjYHb8-1vB0VGaBA',
    appId: '1:664746257926:ios:ef02fc88542bc9e09c5d87',
    messagingSenderId: '664746257926',
    projectId: 'example-33ebf',
    storageBucket: 'example-33ebf.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJHMbOwyEgVRTPbVu4DnU4-ihrvzzihg',
    appId: '1:664746257926:web:b78713d63d1fa9b09c5d87',
    messagingSenderId: '664746257926',
    projectId: 'example-33ebf',
    authDomain: 'example-33ebf.firebaseapp.com',
    storageBucket: 'example-33ebf.firebasestorage.app',
  );
}
